networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.myresolver.acme.email=mycoole-mail@zotmail-changethis.com"
      - "--certificatesResolvers.myresolver.acme.storage=/acme.json"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
    ports:
#      - "80:80"
      - "443:443"
#      - "8080:8080"        # Traefik dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - proxy

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket-id
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/app/data"
    read_only: true
    user: "1000:1000"
    labels:  # <-- fixed indentation
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pocket-id.rule=Host(`subdomain.domain.com`)"
      - "traefik.http.routers.pocket-id.entrypoints=websecure"
      - "traefik.http.routers.pocket-id.tls=true"
      - "traefik.http.routers.pocket-id.tls.certresolver=myresolver"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=80"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=1411"
    networks:
      - proxy
